FROM php:8.3-apache

# Instalace závislostí potřebných pro Composer a rozšíření PHP
RUN apt-get update && apt-get install -y \
        zip \
        unzip \
        git \
        libzip-dev \
        && docker-php-ext-install zip

# Stáhněte a nainstalujte Composer
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

# Instalace Xdebug
RUN pecl install xdebug && \
    docker-php-ext-enable xdebug
    
# Konfigurace Xdebug
RUN echo 'xdebug.mode=debug' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo 'xdebug.remote_autostart=off' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
