services:
  php:
    build: .
    container_name: web
    ports:
      - "80:80"
      - 9000
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    restart: always
    links:
      - mysql
      - mysql-test
    depends_on:
      - mysql
      - mysql-test
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=localhost}
  mysql:
    image: mysql:8.3
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  mysql-test:
    image: mysql:8.3
    container_name: mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testovaci_db
    ports:
      - "3307:3306"
volumes:
  dbdata: