services:
  php:
    build: .
    container_name: web
    ports:
      - "80:80"
      - 9000
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    restart: always
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=localhost}
  mysql:
    image: mysql:8.3
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./sql:/var/dump
volumes:
  dbdata: